#!/usr/bin/env bash
# league-lean bootstrap installer (macOS / Linux).
#
# No git required — uses curl + tar.
#
# Update channel — auto-detected from this file's name:
#   install-league-lean.sh        → main (stable)
#   install-league-lean-dev.sh    → dev  (experimental)
# Override via a sibling file `league-lean.branch` containing a single line.

set -euo pipefail
cd "$(dirname "$0")"

REPO="Nicetyone/league-lean"
DEST="league-lean"
TARBALL="/tmp/league-lean.tar.gz"
EXTRACT="/tmp/league-lean-extract"

BRANCH="main"
BASENAME=$(basename "$0" .sh)
case "$BASENAME" in
  *-dev) BRANCH="dev" ;;
esac
if [ -f "./league-lean.branch" ]; then
  BRANCH=$(head -n1 "./league-lean.branch" | tr -d '[:space:]')
fi

echo
echo "[league-lean] working dir: $PWD"
echo "[league-lean] update branch: $BRANCH"
echo "[league-lean] cleaning previous install..."
rm -rf "$DEST" "$EXTRACT" "$TARBALL"
mkdir -p "$EXTRACT"

echo "[league-lean] downloading $BRANCH.tar.gz..."
curl -sLfo "$TARBALL" "https://github.com/$REPO/archive/refs/heads/$BRANCH.tar.gz"

echo "[league-lean] extracting..."
tar -xzf "$TARBALL" -C "$EXTRACT"
mv "$EXTRACT/league-lean-$BRANCH" "$DEST"

echo "[league-lean] resolving SHA..."
META=$(curl -sLf "https://api.github.com/repos/$REPO/commits/$BRANCH")
SHA=$(printf '%s' "$META" | python3 -c "import json,sys;print(json.load(sys.stdin)['sha'])")
DATE=$(printf '%s' "$META" | python3 -c "import json,sys;print(json.load(sys.stdin)['commit']['committer']['date'])")
SHORT=${SHA:0:7}

cat > "$DEST/version.js" <<EOF
// Auto-generated by install-league-lean.sh — do not edit by hand.
export const VERSION = {
  sha: "$SHA",
  shortSha: "$SHORT",
  date: "$DATE",
  branch: "$BRANCH",
};
EOF

rm -f "$TARBALL"
rm -rf "$EXTRACT"

echo
echo "[league-lean] installed at $SHORT on $BRANCH."
echo "  Quit and relaunch the League client (or press Alt+Shift+R if it's running)."
