@echo off
REM league-lean bootstrap installer + updater (Windows).
REM
REM No git, Node, or other toolchain required — uses curl + PowerShell's
REM Expand-Archive, both shipped with Windows 10/11 by default.
REM
REM Update channel — auto-detected from this file's name:
REM   install-league-lean.bat        → main (stable)
REM   install-league-lean-dev.bat    → dev  (experimental)
REM Power users can override via a sibling file `league-lean.branch`
REM containing a single line, e.g. `dev`.
REM
REM Usage:
REM   1. Drop this file into your Pengu Loader plugins folder.
REM   2. Double-click. After it finishes, fully quit + relaunch the
REM      League client (or press Alt+Shift+R if it's already running).

setlocal
cd /d "%~dp0"

set REPO=Nicetyone/league-lean
set DEST=league-lean
set ZIP=%TEMP%\league-lean.zip
set EXTRACT=%TEMP%\league-lean-extract

REM ---- Branch detection ----
set BRANCH=main
set BAT_BASE=%~n0
if /I "%BAT_BASE:~-4%"=="-dev" set BRANCH=dev
if exist "%~dp0league-lean.branch" (
  for /f "usebackq tokens=*" %%B in ("%~dp0league-lean.branch") do set BRANCH=%%B
)

echo.
echo [league-lean] working dir: %CD%
echo [league-lean] update branch: %BRANCH%

echo [league-lean] cleaning previous install...
if exist "%DEST%"     rmdir /s /q "%DEST%"
if exist "%EXTRACT%"  rmdir /s /q "%EXTRACT%"
if exist "%ZIP%"      del /q       "%ZIP%"

echo [league-lean] downloading %BRANCH%.zip from GitHub...
curl -sLfo "%ZIP%" "https://github.com/%REPO%/archive/refs/heads/%BRANCH%.zip"
if errorlevel 1 (
  echo.
  echo ERROR: download failed. Check internet connection.
  pause
  exit /b 1
)

echo [league-lean] extracting...
powershell -nop -c "Expand-Archive -Path '%ZIP%' -DestinationPath '%EXTRACT%' -Force"
if errorlevel 1 (
  echo.
  echo ERROR: Expand-Archive failed. Need PowerShell + Win10+.
  pause
  exit /b 1
)
move "%EXTRACT%\league-lean-%BRANCH%" "%DEST%" >nul

echo [league-lean] resolving SHA via GitHub API...
for /f "delims=" %%S in ('powershell -nop -c "(Invoke-RestMethod 'https://api.github.com/repos/%REPO%/commits/%BRANCH%').sha"') do set SHA=%%S
for /f "delims=" %%D in ('powershell -nop -c "(Invoke-RestMethod 'https://api.github.com/repos/%REPO%/commits/%BRANCH%').commit.committer.date"') do set CDATE=%%D
set SHORTSHA=%SHA:~0,7%

(
  echo // Auto-generated by install-league-lean.bat — do not edit by hand.
  echo export const VERSION = {
  echo   sha: "%SHA%",
  echo   shortSha: "%SHORTSHA%",
  echo   date: "%CDATE%",
  echo   branch: "%BRANCH%",
  echo };
) > "%DEST%\version.js"

del /q       "%ZIP%"
rmdir /s /q  "%EXTRACT%"

echo.
echo [league-lean] installed at %SHORTSHA% on %BRANCH%.
echo   Quit + relaunch the League client (or Alt+Shift+R if it's running).
echo.
pause
