// Auto-generated from CommunityDragon summoner-spells.json. Static.
// See scripts/regen-assets.sh to refresh after a patch.
export const SPELL_ICONS = {
  1: "/lol-game-data/assets/data/spells/icons2d/summoner_boost.png",
  3: "/lol-game-data/assets/data/spells/icons2d/summoner_exhaust.png",
  4: "/lol-game-data/assets/data/spells/icons2d/summoner_flash.png",
  5: "/lol-game-data/assets/data/spells/icons2d/summoner_backtrack.png",
  6: "/lol-game-data/assets/data/spells/icons2d/summoner_haste.png",
  7: "/lol-game-data/assets/data/spells/icons2d/summoner_heal.png",
  11: "/lol-game-data/assets/data/spells/icons2d/summoner_smite.png",
  12: "/lol-game-data/assets/data/spells/icons2d/summoner_teleport_new.png",
  13: "/lol-game-data/assets/data/spells/icons2d/summonermana.png",
  14: "/lol-game-data/assets/data/spells/icons2d/summonerignite.png",
  21: "/lol-game-data/assets/data/spells/icons2d/summonerbarrier.png",
  30: "/lol-game-data/assets/data/spells/icons2d/benevolence_of_king_poro_icon.png",
  31: "/lol-game-data/assets/data/spells/icons2d/trailblazer_poro_icon.png",
  32: "/lol-game-data/assets/data/spells/icons2d/summoner_mark.png",
  39: "/lol-game-data/assets/data/spells/icons2d/summoner_mark.png",
  54: "/lol-game-data/assets/data/spells/icons2d/summoner_empty.png",
  55: "/lol-game-data/assets/data/spells/icons2d/summoner_emptysmite.png",
  2201: "/lol-game-data/assets/data/spells/icons2d/icon_summonerspell_flee.2v2_mode_fighters.png",
  2202: "/lol-game-data/assets/data/spells/icons2d/summoner_flash.png",
  2203: "/lol-game-data/assets/data/spells/icons2d/summoner_flash.png",
  4294967295: "/lol-game-data/assets/data/spells/icons2d/1103_smite.png",
  4294967295: "/lol-game-data/assets/data/spells/icons2d/1101_smite.png",
  4294967295: "/lol-game-data/assets/data/spells/icons2d/1102_smite.png",
};
